[DefaultOutputDestinationSettings = [DestinationDefinition = [Kind = "Reference", QueryName = "DefaultDestination", IsNewTarget = true], UpdateMethod = [Kind = "Replace"]], StagingDefinition = [Kind = "FastCopy"]]
section Section1;
shared DefaultDestination = Lakehouse.Contents([EnableFolding = false]){[workspaceId = "ce93347d-b2ec-43a6-b193-8736ba31b93e"]}[Data]{[lakehouseId = "7fb4903b-fcac-4f8c-a0f9-0705a22c1ceb"]}[Data];
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Query_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "symbol", DestinationColumnName = "symbol"], [SourceColumnName = "name", DestinationColumnName = "name"], [SourceColumnName = "current_price", DestinationColumnName = "current_price"], [SourceColumnName = "market_cap", DestinationColumnName = "market_cap"], [SourceColumnName = "market_cap_rank", DestinationColumnName = "market_cap_rank"], [SourceColumnName = "fully_diluted_valuation", DestinationColumnName = "fully_diluted_valuation"], [SourceColumnName = "total_volume", DestinationColumnName = "total_volume"], [SourceColumnName = "high_24h", DestinationColumnName = "high_24h"], [SourceColumnName = "low_24h", DestinationColumnName = "low_24h"], [SourceColumnName = "price_change_24h", DestinationColumnName = "price_change_24h"], [SourceColumnName = "price_change_percentage_24h", DestinationColumnName = "price_change_percentage_24h"], [SourceColumnName = "market_cap_change_24h", DestinationColumnName = "market_cap_change_24h"], [SourceColumnName = "market_cap_change_percentage_24h", DestinationColumnName = "market_cap_change_percentage_24h"], [SourceColumnName = "circulating_supply", DestinationColumnName = "circulating_supply"], [SourceColumnName = "total_supply", DestinationColumnName = "total_supply"], [SourceColumnName = "max_supply", DestinationColumnName = "max_supply"], [SourceColumnName = "ath", DestinationColumnName = "ath"], [SourceColumnName = "ath_change_percentage", DestinationColumnName = "ath_change_percentage"], [SourceColumnName = "ath_date", DestinationColumnName = "ath_date"], [SourceColumnName = "atl", DestinationColumnName = "atl"], [SourceColumnName = "atl_change_percentage", DestinationColumnName = "atl_change_percentage"], [SourceColumnName = "atl_date", DestinationColumnName = "atl_date"], [SourceColumnName = "last_updated", DestinationColumnName = "last_updated"]}], DynamicSchema = false, UpdateMethod = [Kind = "Append"], TypeSettings = [Kind = "Table"]]]}]
shared Query = let
  Source = Json.Document(Web.Contents("https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_")),
  #"Converted to table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
  #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to table", "Column1", {"id", "symbol", "name", "image", "current_price", "market_cap", "market_cap_rank", "fully_diluted_valuation", "total_volume", "high_24h", "low_24h", "price_change_24h", "price_change_percentage_24h", "market_cap_change_24h", "market_cap_change_percentage_24h", "circulating_supply", "total_supply", "max_supply", "ath", "ath_change_percentage", "ath_date", "atl", "atl_change_percentage", "atl_date", "roi", "last_updated"}, {"id", "symbol", "name", "image", "current_price", "market_cap", "market_cap_rank", "fully_diluted_valuation", "total_volume", "high_24h", "low_24h", "price_change_24h", "price_change_percentage_24h", "market_cap_change_24h", "market_cap_change_percentage_24h", "circulating_supply", "total_supply", "max_supply", "ath", "ath_change_percentage", "ath_date", "atl", "atl_change_percentage", "atl_date", "roi", "last_updated"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Expanded Column1", {{"id", type text}, {"symbol", type text}, {"name", type text}, {"image", type text}, {"current_price", type number}, {"market_cap", Int64.Type}, {"market_cap_rank", Int64.Type}, {"fully_diluted_valuation", Int64.Type}, {"total_volume", Int64.Type}, {"high_24h", type number}, {"low_24h", type number}, {"price_change_24h", type number}, {"price_change_percentage_24h", type number}, {"market_cap_change_24h", type number}, {"market_cap_change_percentage_24h", type number}, {"circulating_supply", type number}, {"total_supply", type number}, {"max_supply", type number}, {"ath", type number}, {"ath_change_percentage", type number}, {"ath_date", type datetime}, {"atl", type number}, {"atl_change_percentage", type number}, {"atl_date", type datetime}, {"last_updated", type datetime}}),
  #"Expanded roi" = Table.ExpandRecordColumn(#"Changed column type", "roi", {"times", "currency", "percentage"}, {"roi.times", "roi.currency", "roi.percentage"}),
  #"Removed columns" = Table.RemoveColumns(#"Expanded roi", {"image"})
in
  #"Removed columns";
shared Query_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "ce93347d-b2ec-43a6-b193-8736ba31b93e"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "7fb4903b-fcac-4f8c-a0f9-0705a22c1ceb"]}[Data],
  TableNavigation = Navigation_2{[Id = "Query", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
